---
  # This play deploys the project to the virtual hosts.

- name: Deploy Project 0
  hosts: all
  become: yes
  tasks:
  - name: git
    package:
        name: git
        state: present
  - name: python3
    package:
        name: python3
        state: present
  - name: "clone or git pull"
    git:
        repo: https://github.com/2105-may24-devops/anthony-project-0.git
        dest: /home/anthony-project-0
        update: yes